name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Auto Increment Semver Action
        uses: MCKanpolat/auto-semver-action@1.0.5
        id: versioning
        with:
          releaseType: patch 
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Github Release
        uses: actions/create-release@v1
        if: steps['versioning']['outputs']['RETURN_STATUS'] == '0'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.versioning.outputs.version }}
          release_name: ${{ steps.versioning.outputs.version }}
          body: Version ${{ steps.versioning.outputs.version }}
          draft: false
          prerelease: false
      - name: Update pulp-core pin
        run: sed -i "s,FROM kong/pulp-core.*,FROM kong/pulp-core:${{ steps.versioning.outputs.version }},g" */Dockerfile
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build tagged images
        env:
          DOCKER_BUILDKIT: 1
          ORG: kong
          TAG: ${{ steps.versioning.outputs.version }}
        run: |
          make images
      - name: Build latest images
        env:
          DOCKER_BUILDKIT: 1
          ORG: kong
          TAG: latest
        run: |
          make images
      - name: Release latest images
        env:
          ORG: kong
          TAG: latest
        run: |
          make release
      - name: Release tagged images
        env:
          ORG: kong
          TAG: ${{ steps.versioning.outputs.version }}
        run: |
          make release
      - name: Commit back
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: Release ${{ steps.versioning.outputs.version }}
          branch: main
